name: Continuous Integration
on: [push]

jobs:
  build_job:
    runs-on: self-hosted 
    name: build
    steps:
      # check out the repository
      - name: Checkout    
        uses: actions/checkout@v2 

      - name: Install Dependencies
        run: npm i
      - name: Build
        run: npm run build

      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0 
        with:  
          username: 'root'   #ssh user name
          server: '${{ secrets.SERVER_IP }}' 
          port: '${{ secrets.SERVER_PORT }}'
          ssh_private_key: ${{ secrets.SSH_KEY }}
          local_path: './build/*' 
          remote_path: '/var/www/react-app'